// Require/import the HTTP module
//this is an internal node library
var http = require("http");
var insults = ["If laughter is the best medicine, your face must be curing the world.",
	"You're so ugly, you scared the crap out of the toilet.",
	"Your family tree must be a cactus because everybody on it is a prick.",
	"No I'm not insulting you, I'm describing you.",
	"It's better to let someone think you are an Idiot than to open your mouth and prove it.",
	"If I had a face like yours, I'd sue my parents.",
	"Your birth certificate is an apology letter from the condom factory.",
	"I guess you prove that even god makes mistakes sometimes.",
	"The only way you'll ever get laid is if you crawl up a chicken's ass and wait.",
	"You're so fake, Barbie is jealous.",
	"I'm jealous of people that don't know you!",
	"My psychiatrist told me I was crazy and I said I want a second opinion. He said okay, you're ugly too.",
	"You're so ugly, when your mom dropped you off at school she got a fine for littering.",
	"If I wanted to kill myself I'd climb your ego and jump to your IQ.",
	"You must have been born on a highway because that's where most accidents happen.",
	"Brains aren't everything. In your case they're nothing.",
	"I don't know what makes you so stupid, but it really works.",
	"I can explain it to you, but I can't understand it for you.",
	"Roses are red violets are blue, God made me pretty, what happened to you?",
	"Behind every fat woman there is a beautiful woman. No seriously, your in the way.",
	"Calling you an idiot would be an insult to all the stupid people.",
	"You, sir, are an oxygen thief!",
	"Some babies were dropped on their heads but you were clearly thrown at a wall.",
	"Don't like my sarcasm, well I don't like your stupid.",
	"Why don't you go play in traffic.",
	"Please shut your mouth when you're talking to me.",
	"I'd slap you, but that would be animal abuse.",
	"They say opposites attract. I hope you meet someone who is good-looking, intelligent, and cultured.",
	"Stop trying to be a smart ass, you're just an ass.",
	"The last time I saw something like you, I flushed it.",
	"'m busy now. Can I ignore you some other time?",
	"You have Diarrhea of the mouth; constipation of the ideas.",
	"If ugly were a crime, you'd get a life sentence.",
	"Your mind is on vacation but your mouth is working overtime.",
	"I can lose weight, but you'll always be ugly.",
	"Why don't you slip into something more comfortable... like a coma.",
	"Shock me, say something intelligent.",
	"If your gonna be two faced, honey at least make one of them pretty.",
	"Keep rolling your eyes, perhaps you'll find a brain back there.",
	"What you've just said is one of the most insanely idiotic things I have ever heard. At no point in your rambling, incoherent response were you even close to anything that could be considered a rational thought. Everyone in this room is now dumber for having listened to it. I award you no points, and may God have mercy on your soul.",
	"You are not as bad as people say, you are much, much worse.",
	"I don't know what your problem is, but I'll bet it's hard to pronounce.",
	"You get ten times more girls than me? ten times zero is zero...",
	"There is no vaccine against stupidity.",
	"You're the reason the gene pool needs a lifeguard.",
	"Sure, I've seen people like you before - but I had to pay an admission.",
	"How old are you? - Wait I shouldn't ask, you can't count that high.",
	"Have you been shopping lately? They're selling lives, you should go get one.",
	"You're like Monday mornings, nobody likes you.",
	"Of course I talk like an idiot, how else would you understand me?",
	"All day I thought of you... I was at the zoo.",
	"To make you laugh on Saturday, I need to you joke on Wednesday.",
	"You're so fat, you could sell shade.",
	"I'd like to see things from your point of view but I can't seem to get my head that far up my ass.",
	"Don't you need a license to be that ugly?",
	"My friend thinks he is smart. He told me an onion is the only food that makes you cry, so I threw a coconut at his face.",
	"Your house is so dirty you have to wipe your feet before you go outside.",
	"If you really spoke your mind, you'd be speechless.",
	"Stupidity is not a crime so you are free to go.",
	"You are so old, when you were a kid rainbows were black and white.",
	"If I told you that I have a piece of dirt in my eye, would you move?",
	"You so dumb, you think Cheerios are doughnut seeds.",
	"So, a thought crossed your mind? Must have been a long and lonely journey.",
	"You are so old, your birth-certificate expired.",
	"Every time I'm next to you, I get a fierce desire to be alone.",
	"You're so dumb that you got hit by a parked car.",
	"Keep talking, someday you'll say something intelligent!",
	"You're so fat, you leave footprints in concrete.",
	"How did you get here? Did someone leave your cage open?",
	"Pardon me, but you've obviously mistaken me for someone who gives a damn.",
	"Wipe your mouth, there's still a tiny bit of bullshit around your lips.",
	"Don't you have a terribly empty feeling - in your skull?",
	"As an outsider, what do you think of the human race?",
	"Just because you have one doesn't mean you have to act like one.",
	"We can always tell when you are lying. Your lips move.",
	"Are you always this stupid or is today a special occasion?"];

var compliments = ["Your smile is contagious.",
	"You look great today.",
	"You're a smart cookie.",
	"I bet you make babies smile.",
	"You have impeccable manners.",
	"I like your style.",
	"You have the best laugh.",
	"I appreciate you.",
	"You are the most perfect you there is.",
	"You are enough.",
	"You're strong.",
	"Your perspective is refreshing.",
	"You're an awesome friend.",
	"You light up the room.",
	"You deserve a hug right now.",
	"You should be proud of yourself.",
	"You're more helpful than you realize.",
	"You have a great sense of humor.",
	"You've got all the right moves!",
	"Is that your picture next to \"charming\" in the dictionary?",
	"Your kindness is a balm to all who encounter it.",
	"You're all that and a super-size bag of chips.",
	"On a scale from 1 to 10, you're an 11.",
	"You are brave.",
	"You're even more beautiful on the inside than you are on the outside.",
	"You have the courage of your convictions.",
	"Your eyes are breathtaking.",
	"If cartoon bluebirds were real, a bunch of them would be sitting on your shoulders singing right now.",
	"You are making a difference.",
	"You're like sunshine on a rainy day.",
	"You bring out the best in other people.",
	"Your ability to recall random factoids at just the right time is impressive.",
	"You're a great listener.",
	"How is it that you always look great, even in sweatpants?",
	"Everything would be better if more people were like you!",
	"I bet you sweat glitter.",
	"You were cool way before hipsters were cool.",
	"That color is perfect on you.",
	"Hanging out with you is always a blast.",
	"You always know -- and say -- exactly what I need to hear when I need to hear it.",
	"You smell really good.",
	"You may dance like no one's watching, but everyone's watching because you're an amazing dancer!",
	"Being around you makes everything better!",
	"When you say, \"I meant to do that,\" I totally believe you.",
	"When you're not afraid to be yourself is when you're most incredible.",
	"Colors seem brighter when you're around.",
	"You're more fun than a ball pit filled with candy. (And seriously, what could be more fun than that?)",
	"That thing you don't like about yourself is what makes you so interesting.",
	"You're wonderful.",
	"You have cute elbows. For reals! (You're halfway through the list. Don't stop now! You should be giving at least one awesome compliment every day!)",
	"Jokes are funnier when you tell them.",
	"You're better than a triple-scoop ice cream cone. With sprinkles.",
	"Your bellybutton is kind of adorable.",
	"Your hair looks stunning.",
	"You're one of a kind!",
	"You're inspiring.",
	"If you were a box of crayons, you'd be the giant name-brand one with the built-in sharpener.",
	"You should be thanked more often. So thank you!!",
	"Our community is better because you're in it.",
	"Someone is getting through something hard right now because you've got their back. ",
	"You have the best ideas.",
	"You always know how to find that silver lining.",
	"Everyone gets knocked down sometimes, but you always get back up and keep going.",
	"You're a candle in the darkness.",
	"You're a great example to others.",
	"Being around you is like being on a happy little vacation.",
	"You always know just what to say.",
	"You're always learning new things and trying to better yourself, which is awesome.",
	"If someone based an Internet meme on you, it would have impeccable grammar.",
	"You could survive a Zombie apocalypse.",
	"You're more fun than bubble wrap.",
	"When you make a mistake, you fix it.",
	"Who raised you? They deserve a medal for a job well done.",
	"You're great at figuring stuff out.",
	"Your voice is magnificent.",
	"The people you love are lucky to have you in their lives.",
	"You're like a breath of fresh air.",
	"You're gorgeous -- and that's the least interesting thing about you, too.",
	"You're so thoughtful.",
	"Your creative potential seems limitless.",
	"Your name suits you to a T.",
	"You're irresistible when you blush.",
	"Actions speak louder than words, and yours tell an incredible story.",
	"Somehow you make time stop and fly at the same time.",
	"When you make up your mind about something, nothing stands in your way.",
	"You seem to really know who you are.",
	"Any team would be lucky to have you on it.",
	"In high school I bet you were voted \"most likely to keep being awesome.\"",
	"I bet you do the crossword puzzle in ink.",
	"Babies and small animals probably love you.",
	"If you were a scented candle they'd call it Perfectly Imperfect (and it would smell like summer).",
	"There's ordinary, and then there's you.",
	"You're someone's reason to smile.",
	"You're even better than a unicorn, because you're real.",
	"How do you keep being so funny and making everyone laugh?",
	"You have a good head on your shoulders.",
	"Has anyone ever told you that you have great posture?",
	"The way you treasure your loved ones is incredible.",
	"You're really something special.",
	"You're a gift to those around you."];
// Define a port to listen for incoming requests
var PORT_good = 7000;
var PORT_bad = 7500;

// Create a generic function to handle requests and responses
function handleRequestGood(request, response) {
	var output = Math.floor(Math.random() * compliments.length)-1;
  // Send the below string to the client when the user visits the PORT URL
  response.end(compliments[output] + request.url);
}

function handleRequestBad(request, response) {
	var output = Math.floor(Math.random() * insults.length)-1;
  // Send the below string to the client when the user visits the PORT URL
  response.end(insults[output] + request.url);
}

// Use the Node HTTP package to create our server.
// Pass the handleRequest function to empower it with functionality.
var serverGood = http.createServer(handleRequestGood);
var serverBad = http.createServer(handleRequestBad);

// Start our server so that it can begin listening to client requests.
serverGood.listen(PORT_good, function() {

  // Log (server-side) when our server has started
  console.log("Server listening on: http://localhost:" + PORT_good);
});

serverBad.listen(PORT_bad, function() {

  // Log (server-side) when our server has started
  console.log("Server listening on: http://localhost:" + PORT_bad);
})